name: Build and Release Plugin

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'

jobs:
  build:
    name: Build Plugin ZIP
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Create a ZIP file of the plugin
      - name: Build Plugin ZIP
        run: |
          zip -r multisite-version-control.zip . -x '*.git*' -x '*.github*'

      # Step 3: Upload the ZIP file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: multisite-version-control
          path: multisite-version-control.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 4: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 5: Download the built ZIP file from the previous step
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: multisite-version-control
          path: .

      # Step 6: Create a release on GitHub and attach the ZIP file
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: multisite-version-control.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use either GITHUB_TOKEN or your personal token
